require:
  - standard
  - rubocop-rails
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'test/**'
    - 'spec/sample/bin/**'
    - 'vendor/bundle'

Gemspec/RequireMFA:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
