inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'spec/sample/bin/**/*'
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'

Gemspec/RequireMFA:
  Enabled: false
