require:
  - standard
  - rubocop-rails
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  DisabledByDefault: true
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'test/**'
    - 'spec/sample/bin/**/*'
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'

Gemspec/RequireMFA:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
