name: Rubocop

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: default doc job cable storage ujs test db

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: Setup Rubocop
      run: bundle binstubs rubocop

    - name: Run Rubocop
      run: bundle exec rubocop --parallel